### ISSUE TITLE
EvDev D-pad errors.

### ISSUE THREAD

**Issue by ethicalhacker7192** [gvalkov/python-evdev#210]
This is due to lack of documentation, I am struggling in implementing a D-pad feature for my virtual controller:

```py
class VirtualController:
    def __init__(self):
        capabilities = {
            e.EV_KEY: [
                e.BTN_EAST,  # A
                e.BTN_SOUTH,  # B
                e.BTN_NORTH,  # X
                e.BTN_WEST,  # Y
                e.BTN_TL,  # L
                e.BTN_TR,  # R
                e.BTN_SELECT,  # SELECT
                e.BTN_START,  # START
            ],
            e.EV_ABS: [
                (e.ABS_HAT0X, {'min': -1, 'max': 1, 'fuzz': 0, 'flat': 0}),
                (e.ABS_HAT0Y, {'min': -1, 'max': 1, 'fuzz': 0, 'flat': 0}),
            ]
        }

        self.device = UInput(events=capabilities, name="Virt0")
```
            
Does anyone have any pointers on visualizing the D-pad?

**Comment by sezanzeb** [comment]
The error you are getting would be helpful. Is it

```
TypeError: 'str' object cannot be interpreted as an integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mango/.config/JetBrains/PyCharmCE2023.2/scratches/scratch_11.py", line 27, in <module>
    v = VirtualController()
        ^^^^^^^^^^^^^^^^^^^
  File "/home/mango/.config/JetBrains/PyCharmCE2023.2/scratches/scratch_11.py", line 25, in __init__
    self.device = UInput(events=capabilities, name="Virt0")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mango/.local/lib/python3.11/site-packages/evdev/uinput.py", line 152, in __init__
    _uinput.setup(self.fd, name, vendor, product, version, bustype, absinfo, max_effects)
SystemError: <built-in function setup> returned a result with an exception set
```

?

Anyhow, this seems to work for me:

```py
class VirtualController:
    def __init__(self):
        capabilities = {
            e.EV_KEY: [
                e.BTN_EAST,  # A
                e.BTN_SOUTH,  # B
                e.BTN_NORTH,  # X
                e.BTN_WEST,  # Y
                e.BTN_TL,  # L
                e.BTN_TR,  # R
                e.BTN_SELECT,  # SELECT
                e.BTN_START,  # START
            ],
            e.EV_ABS: [
                (e.ABS_HAT0X, AbsInfo(0, -1, 1, 0, 0, 0)),
                (e.ABS_HAT0Y, AbsInfo(0, -1, 1, 0, 0, 0)),
            ]
        }

        self.device = UInput(events=capabilities, name="Virt0")
```

**Comment by ethicalhacker7192** [comment]
Yes.

**Comment by sezanzeb** [comment]
Does the posted solution work for you, can this issue be closed?

**Comment by ethicalhacker7192** [comment]
It works, I'll close the issue immediately.
