### ISSUE TITLE
InputDevice.read() - Recource temporarily unaivalable

### ISSUE THREAD

**Issue by Avraamu** [gvalkov/python-evdev#32]
Hi, 
I'm trying to read out the axis of a "Logitech Cordless RumblePad 2", not without trouble however...
I am able to read out the events coming from the device with .read_loop() (events_get in the sample code) and from read_one.  But I am unable to to read from the read() buffer (get_axis_pos in example).

I'm using Ubuntu 14.04.2 LTS

Dumbed down the code I am using looks like this:
```
import evdev
import logging

controller_name = "Logitech Logitech Cordless RumblePad 2"

logging.basicConfig(level=logging.DEBUG, format="[%(asctime)s] %(threadName)s %(message)s", datefmt="%H:%M:%S")
logging.info("Controller output script started")

def main():
    controller = ControllerInput(controller_name)
    while True:
        controller.get_axis_pos()


class ControllerInput():
    def __init__(self, controller_name):

        devices = [evdev.InputDevice(fn) for fn in evdev.list_devices()]
        logging.debug("Found devices: " + str(len(devices)))

        dev_location = None
        for dev in devices:
            if dev.name == controller_name:
                dev_location = dev.fn
                logging.debug("Found desired device: " + dev.name + " at: " + dev.fn)
                break
        if dev_location is None:
            raise "Device not found!"

        self.dev_obj = evdev.InputDevice(dev_location)
        self.axispos = [128, 128, 128, 128]     #left x,y |right x,y

    def events_get(self):
        for event in self.dev_obj.read_loop():
            if event.type != 0:
                print(event)

    def get_axis_pos(self):
        event_gen = self.dev_obj.read()
        if event_gen is not None:
            for event in event_gen:
                if event.type == 3:
                    if event.code == 0:      #0: left x axis |1: left y axis
                        self.axispos[0] = event.value
                    elif event.code == 1:
                        self.axispos[1] = event.value
                    elif event.code == 2:   #2: right x axis |5: right y axis
                        self.axispos[2] = event.value
                    elif event.code == 5:
                        self.axispos[3] = event.value

        logging.debug("Controller axis: " + str(self.axispos[0]))

if __name__ == "__main__":
    main()
```

The error I get when running this code is:
```
[16:34:26] MainThread Controller output script started
[16:34:26] MainThread Found devices: 1
[16:34:26] MainThread Found desired device: Logitech Logitech Cordless RumblePad 2 at: /dev/input/event13
Traceback (most recent call last):
  File "/media/philip/2.3.1-18-amd64/Projects/pycharm/quadcopter/controller.py", line 139, in <module>
    main()
  File "/media/philip/2.3.1-18-amd64/Projects/pycharm/quadcopter/controller.py", line 48, in main
    controller.get_axis_pos()
  File "/media/philip/2.3.1-18-amd64/Projects/pycharm/quadcopter/controller.py", line 125, in get_axis_pos
    for event in event_gen:
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 246, in read
    events = _input.device_read_many(self.fd)
BlockingIOError: [Errno 11] Resource temporarily unavailable
```

Regards Avraamu

**Comment by gvalkov** [comment]
Hello @Avraamu,

I must admit that the `device.read()` method must be documented more thoroughly. What this exception is telling you is that there is nothing to be read from the input device at the moment. Since the device is opened in non-blocking mode, you first have to check if there is anything that can be read from it. One way to do that is with [select](https://docs.python.org/3/library/select.html#select.select). For example:

```python
from select import select

while True:
    # The select() call will block until there are events on dev_obj.
    r, w, x = select([self.dev_obj], [], [])
    # .read() will surely return a list of events now.
    for event in self.dev_obj.read():
        yield event
```

This is exactly what the `device.read_loop()` method does btw. So, your solution might be as simple as modifying your `main()` function to check if the device is readable:

```python
def main():
    controller = ControllerInput(controller_name)
    while True:
        select([controller.dev_obj], [], [])
        controller.get_axis_pos()

# you may remove the 'if event_gen is not None' line from 'get_axis_pos()'
```

One issue with this approach is that your program will only be able to do things when there are events from the pad. This can be addressed in several ways (e.g. `select` has a `timeout` parameter or you could use a thread for input handling). I think issue #15 also touched on this subject.

Let me know if this helps.

Kind regards,
Georgi

**Comment by Avraamu** [comment]
Hello Georgi,

Thanks for the quick reply!
I'm surprised the solution was so simple! I got the example working as you said, with the select function.
Sorry for bothering you with such simple questions :)

Regards Avraamu
