### ISSUE TITLE
debian 8.0 install through pip

### ISSUE THREAD

**Issue by j41ss** [gvalkov/python-evdev#36]
```python
import evdev
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "evdev/__init__.py", line 7, in <module>
    from evdev.device import DeviceInfo, InputDevice, AbsInfo
  File "evdev/device.py", line 8, in <module>
    from evdev import _input, _uinput, ecodes, util
  File "evdev/ecodes.py", line 42, in <module>
    from evdev import _ecodes
ImportError: cannot import name _ecodes
```
append to man notify about correct global enviroment variable PYTHON_PATH="/usr/local/lib/python2.7/"

**Comment by gvalkov** [comment]
Very strange. I just successfullydid this on a vanilla debian Jessie:

```bash
$ apt-get install python-pip python-dev linux-headers-amd64
$ pip install evdev
$ python -c "import evdev"
```

Could you perhaps post the output of `pip install -vvv evdev` on your system after you `pip uninstall evdev` first?

**Comment by j41ss** [comment]
really strange...  after reboot all find thanks
